name: "Test"

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.board }} ${{ matrix.framework_opts }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        framework_opts:
          - "type=esp-idf"
        board:
          - esp32-c3-devkitm-1
          - esp32-s3-devkitc-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: ${{matrix.framework_opts}} board=${{matrix.board}} envsubst < test/config.yaml.template > test/config.yaml
      - name: Compile
        uses: esphome/build-action@v6
        id: esphome-build
        with:
          yaml-file: test/config.yaml
